### PR TITLE
Multisession

### PR DESCRIPTION
**Pull request by PeterNerlich**
# Pull request questions

## Which issue does this address

Issue number: expanding on #51 ([relevant comment](https://github.com/Senzing/docker-xterm/issues/51#issuecomment-1075178779)), built on #53

## Why was change needed

This PR does not fix any problems and just adds new functionality. The project does become more flexible.

## What does change improve

Currently, connecting to the docker container via browser connects to the same global bash process, even with multiple clients.
This PR spawns a new shell for each session instead.

However, it also allows clients to request a particular session using a query parameter in the URL. Then, if such a pseudo terminal already exists, the client is connected to that session, locally re-creating the previous behaviour without affecting the other sessions.
If the terminal does not exist, the client gets notified of that fact and connected to a new shell instead.

A button was added to the UI to copy the URL to the current session to the clipboard.

### CODE REVIEW

**Comment by PeterNerlich** [comment]
Guessing or using an enumeration attack is deemed to not be a significant security risk by the author, since the same can be easily achieved through a new shell session, because it is running on the same system without additional security measures anyway.

**Comment by PeterNerlich** [comment]
What I'd still like to try before marking this ready for review is to make sessions timeout after 5 minutes (configurable, of course) of inactivity, meaning without any client connected.

**Comment by docktermj** [comment]
This PR is addressing https://github.com/Senzing/docker-xterm/issues/75

**Comment by PeterNerlich** [comment]
Sorry that I'm not replying and helping much. I'm back in the hole where I still mean to continue digging into this myself, but keep pushing it out because other stuff is more urgent. If you want to address this, please feel free to build on the current PR instead of waiting on whether I'll find time. And thank you for the kind interactions over the past months!

**Pull request closed without merging**
